# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66b75a3542f6366365d6f3e19d0ea62ecae5bf9533ebda921c3402931ce5dbf4a0613d47aabdeb6f3e5601ea86d178a40e249cd4efa2dee8cdd117308cb53421

test:
  secret_key_base: 5aa7304fea960e82cc105fb88aa654425f329552ead5757d5d93a00fa275ff9702171f90d71ca2f4feea50e5ade6d6e3049609f390ce64fdcb0442686b1ffd54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
